services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false